name: shop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Network & API
  dio: ^5.9.0

  # State Management
  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.3.5

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # Utilities
  intl: ^0.19.0
  universal_html: ^2.2.4
  uuid: ^4.0.0
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # UI & Animations
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0
  flutter_staggered_animations: ^1.1.1

  # Form & Validation
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0

  # Connectivity
  connectivity_plus: ^6.0.5

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4

  # Device Info
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

  # Testing
  mocktail: ^1.0.4
  mockito: ^5.4.4

flutter:
  uses-material-design: true